config/routes.rb
Rails.application.routes.draw do
  
  resources :games do
    resources :decks
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :game
  
  def bbcode
    "[b]#{title}[/b]\n" +
    "[ImageID=#{imageid}original]\n" +
    "#{runner_bbcode}\n" +
    "HP: #{hp}/#{maxhp}\n" +
    "Deck: #{cards_in_deck}\n" +
    "Trash: #{cards_in_trash}\n" +
    "Hand: #{cards_in_hand}\n" +
    "In Play: #{cards_in_play}\n" +
    (team == "Hero" ? "[/floatleft]" : "") + "[clear]\n"
  end
  
  def runner_bbcode
    case team
    when "Villian"
      "[b]#{variants}[/b]"
    when "Environment"
      ""
    when "Hero"
      "[floatleft][username=#{player}][/floatleft][floatleft]"
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :decks, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
   
  def self.BBTEMPLATE
    "app/views/games/_bbcode.html.erb"
  end
  
  def bbcode
    template = ERB.new File.read(Game.BBTEMPLATE)
    template.result()
  end
  
  def modbb
    "[b][ImageID=1712641original]
    Conquering Alien Warlord[/b]"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def edit
    @deck = Deck.find(params[:id])
  end
  
  def create
    @game = Game.find(params[:game_id])
    @deck = @game.decks.create(deck_params)
    redirect_to game_path(@game)
  end
  
  def update
    @game = Game.find(params[:game_id])
    @deck = @game.decks.find(params[:id])
      
    if @deck.update(deck_params)
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end
  
  def destroy
    @game = Game.find(params[:game_id])
    @deck = @game.decks.find(params[:id])
    @deck.destroy
    redirect_to game_path(@game)
  end
  
  private
    def deck_params
      params.require(:deck).permit(:title,:team,:imageid,:player,:variants,:hp,:maxhp,:cards_in_deck,:cards_in_trash,:cards_in_hand,:cards_in_play)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  String.include CoreExtensions::String::BBCodeTranslate    
  
  def index
    @games = Game.all
  end
  
  def show
    @game = Game.find(params[:id])
  end
  
  def new
    @game = Game.new
  end
  
  def edit
    @game = Game.find(params[:id])
  end
  
  def create
    @game = Game.new(game_params)
      
    if @game.save
      redirect_to @game
    else
      render 'new'
    end
  end
  
  def update
    @game = Game.find(params[:id])
      
    if @game.update(game_params)
      redirect_to @game
    else
      render 'edit'
    end
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    
    redirect_to games_path
  end
  private 
  def game_params
    params.require(:game).permit(:title,:state,:turn)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/decks/_deck.html.erb
<p>
  <strong>Title:</strong>
  <%= deck.title %>
</p>
  
<p>
  <strong>Team:</strong>
  <%= deck.team %>
</p>

<p>
  <%= deck.bbcode.bbcode_translate.html_safe%>
</p>
<p>
  <%= link_to 'Edit Deck', edit_game_deck_path(deck.game,deck) %>
  <%= link_to 'Destroy Deck', [deck.game, deck], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/decks/_form.html.erb
<%= form_for([@game,@game.decks.build]) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :team %><br />
    <%= f.text_field :team %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

  <%= form_for :deck, url: game_deck_path(@deck.game,@deck), :method => :patch do |f|%>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :team %>
    <%= f.select :team, ['Hero','Villian','Environment']%>
  </p>

  <p>
    <%= f.label :imageid %>
    <%= f.text_field :imageid %>
  </p>

  <p>
    <%= f.label :player %>
    <%= f.text_field :player %>
  </p>
  
    <p>
    <%= f.label :variants %>
    <%= f.text_field :variants %>
  </p>
    <p>
    <%= f.label :hp %>
    <%= f.text_field :hp %>
  </p>
    <p>
    <%= f.label :maxhp %>
    <%= f.text_field :maxhp %>
  </p>
    <p>
    <%= f.label :cards_in_deck %>
    <%= f.text_field :cards_in_deck %>
  </p>
    <p>
    <%= f.label :cards_in_trash %>
    <%= f.text_field :cards_in_trash %>
  </p>
    <p>
    <%= f.label :cards_in_hand %>
    <%= f.text_field :cards_in_hand %>
  </p>
    <p>
    <%= f.label :cards_in_play %>
    <%= f.text_field :cards_in_play%>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

<%= link_to 'Back', game_path(@deck.game) %>

app/views/games/_bbcode.html.erb
[b]

Start of Game Summary[/b]


[u]Current Ongoing Villain Effects[/u]
[b]At the start of the Villain turn, if there are no Minions in play, flip Grand Warlord Voss's Villain Character card. (GWV)
At the start of the Villain turn, if there are 10 or more Minions in play, the planet has been overrun by the Thorathian Army. Game over. (GWV)
Reduce Damage to Grand Warlord Voss by 2 for each Minion in play. (GWV)
Whenever Grand Warlord Voss flips, play the top card of the villain deck. (Challenge mode)[/b]

[u]Current Ongoing Hero Effects[/u]
[b][/b]

[u]Current Ongoing Environment Effects[/u]



[b]Grand Warlord Voss[/b]
[b][ImageID=1712641original]
Conquering Alien Warlord[/b]
Villain, Thorathian
Challenge Mode

[color=green]HP: 90 - Highest Villain target[/color]
Deck: 20
Trash: 0
In Play: 6

—Gene-bound Ion Lancer [color=#ff0000]HP 3 - Lowest Villain target[/color]
Minion (Immune to Energy; at end of Villain turn, deals lowest hero 2 Energy)

—Gene-bound Bionaut [color=#ff0000]HP 3 - Lowest Villain target[/color]
Minion (Immune to Toxic; at end of Villain turn, deals lowest hero 2 Toxic)

—Gene-bound Soldier [color=#ff0000]HP 3 - Lowest Villain target[/color]
Minion (Immune to Projectile; at end of Villain turn, deals highest hero 2 Projectile)

—Gene-bound Firesworn [color=#ff0000]HP 3 - Lowest Villain target[/color]
Minion (Immune to Fire; at end of Villain turn, deals highest hero 2 Fire)

—Gene-bound Psi-weaver [color=#ff0000]HP 3 - Lowest Villain target[/color]
Minion (Immune to Psychic; at end of Villain turn, deals each hero 2 Psychic)



[b]Legacy[/b]
[ImageID=1700306original]
[floatleft][username=fanaka66][/floatleft][floatleft]
HP: 32/32
Deck:36
Trash:0
Hand:4
In Play:1
[/floatleft][clear]


[b]Mister Fixer[/b]
[ImageID=1724394original]
[floatleft][username=CrazyRich428][/floatleft][floatleft]
HP: ?/?
Deck:36
Trash:0
Hand:4
In Play:1
[/floatleft][clear]


[b]Haka[/b]
[ImageID=1712526original]
[floatleft][username=ColtsFan76][/floatleft][floatleft]
[color=green]HP: 34/34 - Highest Hero target[/color]
Deck:36
Trash:0
Hand:4
In Play:1
[/floatleft][clear]


[b]The Naturalist[/b]
[ImageID=2000347original]
[floatleft][username=ShawnI][/floatleft][floatleft]
HP: 29/29
Deck:36
Trash:0
Hand:4
In Play:1
[/floatleft][clear]


[b]Tachyon[/b]
[ImageID=1708126original]
[floatleft][username=Archr][/floatleft][floatleft]
[color=#ff0000]HP: 27/27 - Lowest Hero target[/color]
Deck:36
Trash:0
Hand:4
In Play:1
[/floatleft][clear]


[b]Insula Primalis[/b]
[ImageID=1712636original]
[floatleft]Environment[/floatleft][floatleft]|
|
|[/floatleft][floatleft]Deck: 15
Trash: 0
In Play: 0
[/floatleft][clear]


[b][size=12]It is Grand Warlord Voss's turn.[/b][/size]

app/views/games/_form.html.erb
<%= form_for @game do |f| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, 'error') %> prohibited this game from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>
  
  <p>
    <%= f.label :turn %><br>
    <%= f.text_field :turn %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>  
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<%= link_to 'New game', new_game_path %>

<table>
  <tr>
    <th>Title</th>
    <th>State</th>
    <th>Turn</th>
  </tr>
  <% @games.each do |game| %>
  <tr>
    <td><%= game.title %></td>
    <td><%= game.state %></td>
    <td><%= game.turn %></td>
    <td><%= link_to 'Show', game_path(game) %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game_path(game), method: :delete, data: { confirm: 'Are you sure?'} %></td>
  </tr>
  <% end %>
</table>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>State:</strong>
  <%= @game.state %>
</p>

<p>
  <strong>Turn:</strong>
  <%= @game.turn %>
</p>

<h2>Decks</h2>
<%= render @game.decks %>

<h2>Add a deck:</h2>
<%= render 'decks/form' %>

<%= link_to 'Edit', edit_game_path(@game) %>
<%= link_to 'Back', games_path %>

<p>
  <textarea id="bbcode" name="bbcode" style="width:600px; height:300px;">
  <%= @game.bbcode.html_safe %>
  </textarea>
</p>
<p>
  <%= @game.bbcode.bbcode_translate.html_safe %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SotmGm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, rails</h1>
<%= link_to 'Game List', controller: 'games' %>